version: "2.20.2"

services:

  backend:
    image: backend-marvic
    build: .
    depends_on:
      - database
      - redis
    container_name: marvic-api
    ports:
      - "5000:5000"
    volumes:
      - ./:/Marvic_API_REST
    env_file:
      - .env
    networks:
      network:
        ipv4_address: 172.30.0.2

  database:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      - POSTGRES_PASSWORD=Pd6JYU3<keNy=\0~eTQ38r-D?~"1>jfp2~-00;8Z3tS"i7%u.C
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    networks:
      network:
        ipv4_address: 172.30.0.3

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    environment:
      - REDIS_PORT=6379
      - REDIS_DATABASES=16
    networks:
      network:
        ipv4_address: 172.30.0.4

  adminer:
    image: adminer
    restart: always
    ports:
      - "3456:8080"
    networks:
      network:
        ipv4_address: 172.30.0.5



networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/24
